### ISSUE TITLE
[Feature Request] Screenshot ordering

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#1]
![image](https://user-images.githubusercontent.com/42502676/99613806-bd3aac80-29c4-11eb-9eda-119c7ef1bb2e.png)
Here is an example of a job output. As an encoder it is simpler to flip through all the same screenshot and chose the best one.

Can you either 
1- put each frame in its own folder like this https://i.imgur.com/aVeGzP9.png

2- name files {framenumber}{currentfilename}.png

**Comment by vonhoro** [comment]
They were renamed now they will look like this 
<img width="647" alt="mstsc_9BMFjC38a9" src="https://i.imgur.com/AofnI6S.png">
I will leave the issue open if you want another change about that

**Comment by Motophan** [comment]
This is great
