### ISSUE TITLE
[HIGH PRIORITY] [Feature Request] Comparison screenshots & upload template.

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#12]
This is the reason I need this autoencoder, specifically because comparison screens are extremely time consuming. 

[mediainfo]
MEDIAINFO-PASTE-HERE
[/mediainfo]

[hide=x264 log]
X264-LOG-PASTE-HERE
[/hide]

[comparison=Source, Encode]

https://SOURCEURL https://ENCODEURL
https://SOURCEURL https://ENCODEURL
https://SOURCEURL https://ENCODEURL
https://SOURCEURL https://ENCODEURL
https://SOURCEURL https://ENCODEURL
https://SOURCEURL https://ENCODEURL

[/comparison]

[u][b]Screenshots[/b][/u]

https://ENCODEURL
https://ENCODEURL
https://ENCODEURL
https://ENCODEURL
If I am using any filters use this template.
[mediainfo]
MEDIAINFO-PASTE-HERE
[/mediainfo]

[hide=x264 log]
X264-LOG-PASTE-HERE
[/hide]

or 

[hide=encoder's notes]
paste vapoursynth script here
[/hide]

[comparison=Source, Filtered, Encode]

https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL
https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL
https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL
https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL
https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL
https://SOURCEURL https://SOURCEURLFILTERED https://ENCODEURL

[/comparison]

[u][b]Screenshots[/b][/u]

https://ENCODEURL
https://ENCODEURL
https://ENCODEURL
https://ENCODEURL

To get the https://ENCODEURL
run
ptpimg_uploader -k keygoeshere C:\path\to\encodescreenshot.png

and this echo's a url. We need those. 
Also, this program has a very small chance to fail and not give a https://ptpimg.me link so you need to build logic to upload these later. 

to install this, use pip3 install ptpimg_uploader or pip install ptpimg_uploader

**Comment by vonhoro** [comment]
Right now after you finished encoidng use createComparitions.js , you run it with node createComparitions.js
Youll need to have ptpimg_uploader installed  in the same place or have it in path.

**Comment by vonhoro** [comment]
Implemented
