### ISSUE TITLE
[Bugfix] Video is not 10000 frames

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#14]
Its not figuring the video 
![image](https://user-images.githubusercontent.com/42502676/100192317-35f6a880-2e9e-11eb-8565-e8fff9a90299.png)
is 10000 frames

**Comment by Motophan** [comment]
![image](https://user-images.githubusercontent.com/42502676/100192372-4d359600-2e9e-11eb-9c00-4748a564b0e7.png)

**Comment by vonhoro** [comment]
The number is 100.000 not 10.000, I lower it to 80100. I have plans on improving this to work with any video, even a short one, where the user will input similar settings to the crf test, Right now I am testing  what values should be fixed (like the length) what intervals to actually take depending on the size of the video and other stuff

**Comment by Motophan** [comment]
https://i.imgur.com/uFx8NVh.png  :(

**Comment by vonhoro** [comment]
well doing some math, 48 min 22 seconds are 2909seconds and the movie has 24 frames per second so it has around 70000 frames. I will do some work around this to accept any length video as I said in the last post.

**Comment by vonhoro** [comment]
Now it will work in any video
