### ISSUE TITLE
[Feature Request] Default x264 encoding settings

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#3]
Always, 100% of the time, we will use these settings no matter what. There is zero variation whatsoever w/ these. 

The only ones u can mechanically change is `min keyint`, so grep mediainfo and >23 frame rate use 24, >29 frame rate use 30, and variable frame rate use 30. All others *should* *be* *hardcoded*

--level 4.1
--b-adapt 2 
--min-keyint [should typically be the frame rate of your video, e.g. if you were encoding 23.976fps content, then you use 24. This is setting the minimum distance between I-frames.]
--vbv-bufsize 78125 
--vbv-maxrate 62500 
--rc-lookahead 250 
--me tesa
--direct auto 
--subme 11
--trellis 2
--no-dct-decimate 
--no-fast-pskip 
--ref [4/9/12/16] # 1080p=4, 720p=9, 576p=12, 480p=16

**Comment by vonhoro** [comment]
Should I add this settings to every test ?

**Comment by Motophan** [comment]
The way you are testing is fine, but this should be the outputted encode settings. We will never ever ever change these values ever.

**Comment by vonhoro** [comment]
Implemented
Only for the tests
