### ISSUE TITLE
[Feature Request] Limit changeable x264 settings

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#4]
During the pick x264 settings, please add a "Do you want to use p2p templated x264 settings" y/n

Then the ONLY x264 settings we change are the ones we test for (see issue https://github.com/vonhoro/Automate-encoding/issues/3 )

MECHANICALLY TESTED / AUTOCOMPUTED
--crf [14-22]
--bframes [6-16] (see https://github.com/vonhoro/Automate-encoding/issues/6 )

HUMAN LOOK AT SCREENSHOT
--deblock [-3:-3 to 3:3]
--qcomp [0.6 (default) to 0.8]
--aq-mode [1 to 3]
--aq-strength [0.5 to 1.3]
--psy-rd [0.8 to 1.15:0 to 0.15] 

Then have it prompt for each setting.

**Comment by vonhoro** [comment]
with --deblovk should I go
 -3:-3  -3:-2 -3:-1  . . . 
or  -3:-3 -2:-2 . . .
with psy-rd should it be
0.8:0 0.85:0 0.90:0  . . . 1.5:0 0.8:0.5 0.8:1 . . . 1.5:0.15
?

**Comment by Motophan** [comment]
go ahead and do it this way

--deblock does not need to be tested unless it is anime.
Maybe [is this anime y/n?]
and y triggers this test.

It is ok if needlessly tested, no harm. 

if its anime, test -3:-3, -2:-3, -3:-2, -2:-2 no more.

the way you explained testing psyrd is fine

**Comment by vonhoro** [comment]
Implemented
